<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sky.Sim</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sky.Sim.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sky.Session\Sky.Session.csproj" />
  </ItemGroup>
</Project>
