<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sky.Scripting</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sky.Scripting.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LuaCSharp" />
    <PackageReference Include="LuaCSharp.SourceGenerator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sky.Engine\Sky.Engine.csproj" />
  </ItemGroup>
</Project>
